const mbtiToSociotypeMappings = {
    'ENFP': ['IEE', 'EIE', 'ILE'],
    'ENTP': ['ILE', 'EIE', 'LIE', 'IEE'],
    'INFP': ['EII', 'ESI', 'IEI'],
    'INTP': ['LII', 'ILI', 'ILE'],
    'ENFJ': ['EIE', 'ESE', 'IEE'],
    'ENTJ': ['LIE', 'LSE', 'SLE', 'LSI'],
    'INFJ': ['IEI', 'EII', 'ILI'],
    'INTJ': ['ILI', 'LII',],
    'ESFP': ['SEE', 'ESE', 'SLE'],
    'ESTP': ['SLE', 'SEE'],
    'ISFP': ['ESI', 'EII', 'SEI'],
    'ISTP': ['LSI', 'SLI'],
    'ESFJ': ['ESE', 'EIE'],
    'ESTJ': ['LSE', 'LIE', 'LSI', 'SLE'],
    'ISFJ': ['SEI', 'EII', 'ESI'],
    'ISTJ': ['SLI', 'LSI']
};

const mbtiToEnneagramMappings = {
    'INTJ': ['SP5', 'SO5', 'SX5', 'SO6'],
    'INTP': ['SP5', 'SO5', 'SX5', 'SP6', 'SO6'],
    'ENTJ': ['SO1', 'SX1', 'SP3', 'SO3', 'SX6', 'SP7', 'SP8', 'SO8'],
    'ENTP': ['SO5', 'SP7', 'SO7', 'SX7'],
    'INFJ': ['SP4', 'SO4', 'SP5', 'SX5', 'SP6'],
    'INFP': ['SP4', 'SO4', 'SX4', 'SP6'],
    'ENFJ': ['SO2', 'SX2', 'SO3', 'SO7', 'SX7'],
    'ENFP': ['SX4', 'SO7', 'SX7'],
    'ISTJ': ['SP5', 'SO6', 'SP9'],
    'ISFJ': ['SP1', 'SP6', 'SO9', 'SX9'],
    'ESTJ': ['SP1', 'SO1', 'SX1', 'SP3', 'SO3', 'SP8', 'SO8'],
    'ESFJ': ['SP2', 'SO2', 'SX2', 'SO3', 'SX3', 'SO7', 'SO9'],
    'ISTP': ['SP5', 'SO6', 'SX6', 'SP9'],
    'ISFP': ['SP4', 'SO4', 'SX4', 'SX9'],
    'ESTP': ['SO3', 'SP7', 'SP8', 'SO8', 'SX8'],
    'ESFP': ['SX3', 'SP7', 'SP8', 'SO8', 'SX8']
};

const mbtiToPsychosophyMappings = {
    'INTP': ['LVEF', 'LVFE', 'LEVF', 'LEFV', 'LFVE', 'LFEV', 'VLEF', 'VLFE', 'ELVF', 'ELFV', 'FLVE', 'FLEV'],
    'ENTP': ['VLEF', 'VLFE', 'LVEF', 'LVFE', 'LEVF', 'LEFV', 'LFVE', 'LFEV', 'VELF', 'VEFL', 'ELVF', 'ELFV', 'FLVE', 'FLEV'],
    'INTJ': ['LVEF', 'LVFE', 'VLEF', 'VLFE', 'LEVF', 'LEFV', 'LFVE', 'LFEV', 'VFLE', 'VFEL', 'FLVE', 'FLEV'],
    'ENTJ': ['VLEF', 'VLFE', 'VFLE', 'VFEL', 'LVEF', 'LVFE', 'LEVF', 'LEFV', 'LFVE', 'LFEV', 'VELF', 'VEFL'],
    'INFP': ['VELF', 'EVLF', 'ELVF', 'LVFE', 'LEVF', 'LEFV', 'VLFE', 'VEFL', 'EVFL', 'ELFV', 'EFVL', 'EFLV', 'FVEL', 'FVLE', 'FEVL', 'FELV'],
    'ENFP': ['VELF', 'VLEF', 'EVLF', 'EVFL', 'ELVF', 'ELFV', 'LEVF', 'LEFV', 'VEFL', 'EFVL', 'EFLV', 'FVEL', 'FVLE', 'FEVL', 'FELV'],
    'INFJ': ['VELF', 'VLEF', 'EVLF', 'EVFL', 'ELVF', 'ELFV', 'LEVF', 'LEFV', 'VEFL', 'EFVL', 'EFLV', 'FVEL', 'FVLE', 'FEVL', 'FELV'],
    'ENFJ': ['VELF', 'VLEF', 'EVLF', 'EVFL', 'ELVF', 'ELFV', 'LEVF', 'LEFV', 'VEFL', 'EFVL', 'EFLV', 'FVEL', 'FVLE', 'FEVL', 'FELV'],
    'ISTP': ['LFVE', 'LFEV', 'FVEL', 'FVLE', 'FLVE', 'FLEV', 'LVEF', 'LVFE', 'VLEF', 'VLFE', 'VFLE', 'VFEL'],
    'ESTP': ['VFLE', 'VFEL', 'FVEL', 'FVLE', 'LFVE', 'LFEV', 'VLEF', 'VLFE', 'VEFL', 'EVFL', 'EFVL', 'EFLV', 'FLVE', 'FLEV'],
    'ISFP': ['EFVL', 'EFLV', 'FVEL', 'FVLE', 'FEVL', 'FELV', 'VELF', 'VEFL', 'EVLF', 'EVFL', 'ELFV'],
    'ESFP': ['VEFL', 'EVFL', 'EFVL', 'EFLV', 'FVEL', 'FVLE', 'FEVL', 'FELV', 'VELF', 'VFLE', 'VFEL', 'EVLF', 'ELFV'],
    'ISTJ': ['LFVE', 'LFEV', 'FVEL', 'FVLE', 'FLVE', 'FLEV', 'LVEF', 'LVFE', 'EFVL', 'EFLV'],
    'ESTJ': ['LFVE', 'LFEV', 'FVEL', 'FVLE', 'FLVE', 'FLEV', 'LVEF', 'LVFE', 'VLEF', 'VLFE', 'VFLE', 'VFEL'],
    'ISFJ': ['EFVL', 'EFLV', 'FVEL', 'FVLE', 'FEVL', 'FELV', 'LFVE', 'LFEV', 'VELF', 'VEFL', 'EVLF', 'EVFL', 'ELFV'],
    'ESFJ': ['EFVL', 'EFLV', 'FVEL', 'FVLE', 'FEVL', 'FELV', 'VELF', 'VEFL', 'EVLF', 'EVFL', 'ELFV']
};

const enneagramToSocioMappings = {
    'ILE': ['SO5', 'SP7', 'SO7'],
    'SEI': ['SP6', 'SO9', 'SX9'],
    'ESE': ['SP2', 'SX2', 'SX3', 'SO9'],
    'LII': ['SP5', 'SO5', 'SO6'],
    'EIE': ['SO2', 'SO3', 'SX4', 'SO7'],
    'LSI': ['SO1', 'SX1', 'SO6', 'SX6'],
    'SLE': ['SO3', 'SP8', 'SO8', 'SX8'],
    'IEI': ['SO4', 'SX5'],
    'SEE': ['SX2', 'SO3', 'SP7', 'SO8', 'SX8'],
    'ILI': ['SP5', 'SO5', 'SX5'],
    'LIE': ['SP3', 'SO3', 'SO1', 'SP7', 'SO7'],
    'ESI': ['SP1', 'SP4', 'SX4'],
    'LSE': ['SP1', 'SX1', 'SO1', 'SP3', 'SP8'],
    'EII': ['SP4', 'SO4', 'SP6'],
    'IEE': ['SX7', 'SO7'], 
    'SLI': ['SP5', 'SP9']
};

const enneagramToPsychosophyMappings = {
    'sp1': ['LVFE', 'EVFL', 'VLFE', 'VFEL', 'LVEF'],
    'so1': ['LVFE', 'VLFE'],
    'sx1': ['VLFE', 'VFLE', 'VFEL'],
    'sp2': ['EFVL', 'EFLV', 'FELV', 'FEVL'],
    'so2': ['VEFL', 'VELF'],
    'sx2': ['EFVL', 'FEVL'],
    'sp3': ['FVLE', 'VLFE', 'VFLE'],
    'so3': ['FVLE', 'FLVE', 'VFLE', 'VFEL', 'FEVL'],
    'sx3': ['FELV', 'FEVL'],
    'sp4': ['EVFL', 'EFLV', 'VFEL', 'FVEL'],
    'so4': ['EVLF', 'ELVF', 'EVFL'],
    'sx4': ['ELVF', 'EFVL'],
    'sp5': ['LFEV', 'LVEF', 'LEVF', 'FLEV'],
    'so5': ['VLEF', 'LVEF',],
    'sx5': ['LFEV', 'LEFV', 'LVEF', 'LEVF'],
    'sp6': ['LEFV'],
    'so6': ['LVFE', 'LFVE', 'LVEF'],
    'sx6': ['FLVE', 'LFVE'],
    'sp7': ['FVLE', 'FLVE', 'VLFE', 'FLEV'],
    'so7': ['EVLF', 'VLEF', 'VELF'],
    'sx7': ['EVLF', 'ELVF', 'ELFV'],
    'sp8': ['VFLE', 'VFEL'],
    'so8': ['FVLE', 'VFLE', 'VFEL'],
    'sx8': ['VFLE', 'VFEL'],
    'sp9': ['FLEV', 'FELV', 'FVEL'],
    'so9': ['EVFL', 'EFLV', 'FELV'],
    'sx9': ['EFLV', 'FELV']
};
